erp:
  devMode: false

server:
  port: 80

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/erp?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true #url
      username: root  #用户名
      password: 123456  #密码
jwt:
  config:
    key: 49c089f061d4d546f259a14b49c35249
    ttl: 604800000 # 7天
